version: '3.7'

services:
  apache:
    build: .docker/apache
    container_name: ${PROJECT_NAME}_apache
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - .:/var/www/app:cached
    depends_on:
      - php
    networks:
      - backend
      - grid

  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${PROJECT_PORT}:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: EVHEayI6axNl0Z8k
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"

  php:
    build:
      context: .docker/php
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - .:/var/www/app:cached
    depends_on:
      - mysql
    networks:
      - backend
      - grid

  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: ${PROJECT_NAME}_selenium_hub
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"
    networks:
      - backend
      - grid

  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    container_name: ${PROJECT_NAME}_chrome
    shm_size: "2gb"
    ports:
      - "4446:5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=${PROJECT_NAME}_selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - VNC_NO_PASSWORD=1
    depends_on:
      - selenium-hub
    networks:
      - backend
      - grid

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20220427
    container_name: ${PROJECT_NAME}_video_chrome
    volumes:
      - ./.docker/test/recording:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=behat_chrome.mp4
    networks:
      - backend
      - grid

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    container_name: ${PROJECT_NAME}_firefox
    shm_size: "2gb"
    ports:
      - "4447:5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=${PROJECT_NAME}_selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - VNC_NO_PASSWORD=1
    depends_on:
      - selenium-hub
    networks:
      - backend
      - grid

  firefox_video:
    container_name: ${PROJECT_NAME}_video_firefox
    image: selenium/video:ffmpeg-4.3.1-20220427
    volumes:
      - ./.docker/test/recording:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=behat_firefox.mp4
    networks:
      - backend
      - grid

networks:
  backend:
  grid:
